//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieColour {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieColour.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced options.
        /// </summary>
        public static string AdvancedOptions {
            get {
                return ResourceManager.GetString("AdvancedOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse every X-th frame.
        /// </summary>
        public static string AnalyseXthFrame {
            get {
                return ResourceManager.GetString("AnalyseXthFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis finished.
        /// </summary>
        public static string AnalysisFinished {
            get {
                return ResourceManager.GetString("AnalysisFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis selection.
        /// </summary>
        public static string AnalysisSelection {
            get {
                return ResourceManager.GetString("AnalysisSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis started.
        /// </summary>
        public static string AnalysisStarted {
            get {
                return ResourceManager.GetString("AnalysisStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average of the entire frame.
        /// </summary>
        public static string AvgFrame {
            get {
                return ResourceManager.GetString("AvgFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bucket count (per axis).
        /// </summary>
        public static string BucketCount {
            get {
                return ResourceManager.GetString("BucketCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buckets.
        /// </summary>
        public static string Buckets {
            get {
                return ResourceManager.GetString("Buckets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average of &apos;blackest&apos; and &apos;whitest&apos; colour.
        /// </summary>
        public static string BucketsAvgMinMax {
            get {
                return ResourceManager.GetString("BucketsAvgMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average of all colours.
        /// </summary>
        public static string BucketsAvgTotal {
            get {
                return ResourceManager.GetString("BucketsAvgTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        public static string BucketsMedian {
            get {
                return ResourceManager.GetString("BucketsMedian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The operation was cancelled.
        /// </summary>
        public static string CancellationMessage {
            get {
                return ResourceManager.GetString("CancellationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose file.
        /// </summary>
        public static string ChooseFile {
            get {
                return ResourceManager.GetString("ChooseFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion.
        /// </summary>
        public static string Conversion {
            get {
                return ResourceManager.GetString("Conversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion finished.
        /// </summary>
        public static string ConversionFinished {
            get {
                return ResourceManager.GetString("ConversionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion started.
        /// </summary>
        public static string ConversionStarted {
            get {
                return ResourceManager.GetString("ConversionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create images using the selected methods.
        /// </summary>
        public static string CreateImagesUsingMethods {
            get {
                return ResourceManager.GetString("CreateImagesUsingMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating images.
        /// </summary>
        public static string CreatingImages {
            get {
                return ResourceManager.GetString("CreatingImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop found: {0}.
        /// </summary>
        public static string CropFound {
            get {
                return ResourceManager.GetString("CropFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted directory: {0}.
        /// </summary>
        public static string DeletedDirectory {
            get {
                return ResourceManager.GetString("DeletedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted file: {0}.
        /// </summary>
        public static string DeletedFile {
            get {
                return ResourceManager.GetString("DeletedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting converted, temporary movie file.
        /// </summary>
        public static string DeletingTmpMovieFile {
            get {
                return ResourceManager.GetString("DeletingTmpMovieFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting temporary movie frames.
        /// </summary>
        public static string DeletingTmpMovieFrames {
            get {
                return ResourceManager.GetString("DeletingTmpMovieFrames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete byproducts.
        /// </summary>
        public static string DelteByproducts {
            get {
                return ResourceManager.GetString("DelteByproducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detecting crop.
        /// </summary>
        public static string DetectingCrop {
            get {
                return ResourceManager.GetString("DetectingCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elapsed.
        /// </summary>
        public static string Elapsed {
            get {
                return ResourceManager.GetString("Elapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable conversion.
        /// </summary>
        public static string EnableConversion {
            get {
                return ResourceManager.GetString("EnableConversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable extraction.
        /// </summary>
        public static string EnableExtraction {
            get {
                return ResourceManager.GetString("EnableExtraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFmpeg and/or FFprobe are not available on this system. Please install them and/or add them to your PATH..
        /// </summary>
        public static string ErrFfmpegNotAvailablePlsInstall {
            get {
                return ResourceManager.GetString("ErrFfmpegNotAvailablePlsInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must select at least one analysis method.
        /// </summary>
        public static string ErrorMustSelectAnalysisMethod {
            get {
                return ResourceManager.GetString("ErrorMustSelectAnalysisMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error checking if {0} is available.
        /// </summary>
        public static string ErrWhileCheckCmdAvailable {
            get {
                return ResourceManager.GetString("ErrWhileCheckCmdAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est. remaining: {0} min.
        /// </summary>
        public static string EstRemaining {
            get {
                return ResourceManager.GetString("EstRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction.
        /// </summary>
        public static string Extraction {
            get {
                return ResourceManager.GetString("Extraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction finished.
        /// </summary>
        public static string ExtractionFinished {
            get {
                return ResourceManager.GetString("ExtractionFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction started.
        /// </summary>
        public static string ExtractionStarted {
            get {
                return ResourceManager.GetString("ExtractionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string FilterAllFiles {
            get {
                return ResourceManager.GetString("FilterAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video files.
        /// </summary>
        public static string FilterVideoFiles {
            get {
                return ResourceManager.GetString("FilterVideoFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Resizer.
        /// </summary>
        public static string ImageResizer {
            get {
                return ResourceManager.GetString("ImageResizer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase brightness (in %.
        /// </summary>
        public static string IncreaseBrightness {
            get {
                return ResourceManager.GetString("IncreaseBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file.
        /// </summary>
        public static string InputFile {
            get {
                return ResourceManager.GetString("InputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median of the entire frame.
        /// </summary>
        public static string MedianFrame {
            get {
                return ResourceManager.GetString("MedianFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most Frequent colour.
        /// </summary>
        public static string MostFrequent {
            get {
                return ResourceManager.GetString("MostFrequent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie Colour.
        /// </summary>
        public static string MovieColour {
            get {
                return ResourceManager.GetString("MovieColour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple files.
        /// </summary>
        public static string MultipleFilesSelected {
            get {
                return ResourceManager.GetString("MultipleFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output images resolution.
        /// </summary>
        public static string OutputResolution {
            get {
                return ResourceManager.GetString("OutputResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing file: {0}.
        /// </summary>
        public static string ProcessingFile {
            get {
                return ResourceManager.GetString("ProcessingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapid / compressed.
        /// </summary>
        public static string Rapid {
            get {
                return ResourceManager.GetString("Rapid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset to Default values.
        /// </summary>
        public static string ResetDefaultBtn {
            get {
                return ResourceManager.GetString("ResetDefaultBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default values restored.
        /// </summary>
        public static string RestoredDefaultValues {
            get {
                return ResourceManager.GetString("RestoredDefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save output log to file.
        /// </summary>
        public static string SaveOutputLog {
            get {
                return ResourceManager.GetString("SaveOutputLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected files.
        /// </summary>
        public static string SelectedFiles {
            get {
                return ResourceManager.GetString("SelectedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show log.
        /// </summary>
        public static string ShowOutputLog {
            get {
                return ResourceManager.GetString("ShowOutputLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully analysed the following movie(s):.
        /// </summary>
        public static string SuccessAnalysedMovies {
            get {
                return ResourceManager.GetString("SuccessAnalysedMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use GPU for conversion/extraction.
        /// </summary>
        public static string UseGPU {
            get {
                return ResourceManager.GetString("UseGPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working scale.
        /// </summary>
        public static string WorkingScale {
            get {
                return ResourceManager.GetString("WorkingScale", resourceCulture);
            }
        }
    }
}
